# The workflow to test the 
name:  React.js Main -Development

on:
    push:
        branches: [main]

jobs:
    # BUILD THE REACT APPLICATION
    build_test:
        name: Test the Main branch of {React App}
        runs-on: ubuntu-latest
        environment: dev

        steps:

        # Checkout Github Repo
        -   name: 'Checkout GitHub Action'
            uses: actions/checkout@v3                
                
        # Setup Node Environment
        -   name: Setup Node ${{ env.NODE_VERSION }} Environment
            uses: actions/setup-node@v3
            with: 
                node-version: ${{ env.NODE_VERSION }}
        
        # install applicaion dependencies
        -   name: 'Install Dependencies'
            run: |
                npm install
        # build and test the apps
        -   name: 'Build React App'
            run: |
                npm run build
                npm test

        
    
    # PUSH TO DOCKER REPOSITORY
    push_to_docker:
        name: Push to Docker Hub
        runs-on: ubuntu-latest
        needs: [build_test]

        steps:
        
        # Setup Docker Quick EMUlator
        -   name: Setup QEMU
            uses: docker/setup-qemu-action@v2
        
        # Setup Docker Buildx
        -   name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v2
        
        # Login with Docker
        -   name: Login to Docker
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_REACT_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
        # Checkout Github Repo
        -   name: Checkout
            uses: actions/checkout@v2
        
        # -   name: Build Docker image
        #     run: |
        #         ls
        #         docker build . -t ${{ secrets.DOCKER_REACT_USERNAME }}/hello-lantern:latest -f ./Dockerfile
 
        # Docker Build and Push the Commit to Docker Hub
        -   name: Docker Build and Push
            uses: docker/build-push-action@v4
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags:  ${{ secrets.DOCKER_REACT_USERNAME }}/hello-lantern:latest

        # Run the Container 
        -   name: Run the image in a container
            uses: addnab/docker-run-action@v3
            with:
                image: ${{ secrets.DOCKER_REACT_USERNAME }}/hello-lantern:latest
                options: '--name First_App -d -p 80:3000'
                
            
    azure_deployment:
        runs-on: ubuntu-latest
        needs: [push_to_docker]
        steps:
            -   name: 'Login via Azure CLI'
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_CREDENTIALS }}

            -   name: 'Deploy on Web App Container'
                uses: azure/webapps-deploy@v2
                with:
                    app-name: 'demolantern'
                    images: ${{ secrets.DOCKER_REACT_USERNAME }}/hello-lantern:latest
            
            -   name: "Azure logout"
                run: |
                    az logout


        
        